export const USER_LOGIN_SUCCEEDED = 'USER_LOGIN_SUCCEEDED';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USERS_LOADING = 'USERS_LOADING';
export const USERS_GET_SUCCEEDED = 'USERS_GET_SUCCEEDED';
export const USERS_GET_FAILED = 'USERS_GET_FAILED';

export const USER_CLEAR = 'USER_CLEAR';
export const USER_ADD = 'USER_ADD';
export const USER_EDIT = 'USER_EDIT';

export const USER_DELETING = 'USER_DELETING';
export const USER_DELETE_SUCCEEDED = 'USER_DELETE_SUCCEEDED';
export const USER_DELETE_FAILED = 'USER_DELETE_FAILED'; 

export const CDOFFERINGS_LOADING = 'CDOFFERINGS_LOADING';
export const CDOFFERINGS_GET_SUCCEEDED = 'CDOFFERINGS_GET_SUCCEEDED';
export const CDOFFERINGS_GET_FAILED = 'CDOFFERINGS_GET_FAILED';

export const CDOFFERING_CLEAR = 'CDOFFERING_CLEAR';
export const CDOFFERING_ADD = 'CDOFFERING_ADD';

export const CDOFFERING_EDITING = 'CDOFFERING_EDITING';
export const CDOFFERING_EDIT_SUCCEEDED = 'CDOFFERING_EDIT_SUCCEEDED';
export const CDOFFERING_EDIT_FAILED = 'CDOFFERING_EDIT_FAILED';

export const CDOFFERING_DELETE = 'CDOFFERING_DELETE';

export const ACCOUNTHOLDERS_LOADING = 'ACCOUNTHOLDERS_LOADING';
export const ACCOUNTHOLDERS_GET_SUCCEEDED = 'ACCOUNTHOLDERS_GET_SUCCEEDED';
export const ACCOUNTHOLDERS_GET_FAILED = 'ACCOUNTHOLDERS_GET_FAILED';

export const ACCOUNTHOLDER_ADD = 'ACCOUNTHOLDER_ADD';
export const ACCOUNTHOLDER_EDIT = 'ACCOUNTHOLDER_EDIT';
export const ACCOUNTHOLDER_DELETE = 'ACCOUNTHOLDER_DELETE';

export const AHDATA_FAILED = 'AHDATA_FAILED';
export const ADD_AHDATA = 'ADD_AHDATA';
export const AHDATA_LOADING = 'AHDATA_LOADING';