export const USER_AUTHENTICATION_REQUEST = 'USER_AUTHENTICATION_REQUEST';
export const USER_AUTHENTICATION_SUCCEEDED = 'USER_AUTHENTICATION_SUCCEEDED';
export const USER_AUTHENTICATION_FAILED = 'USER_AUTHENTICATION_FAILED';