export const USER_LOGIN_SUCCEEDED = 'USER_LOGIN_SUCCEEDED';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USERS_LOADING = 'USERS_LOADING';
export const USERS_GET_SUCCEEDED = 'USER_GET_SUCCEEDED';
export const USERS_GET_FAILED = 'USER_GET_FAILED';

export const USER_ADD = 'USER_ADD';

export const AHDATA_FAILED = 'AHDATA_FAILED';
export const ADD_AHDATA = 'ADD_AHDATA';
export const AHDATA_LOADING = 'AHDATA_LOADING';